mybatis:
  configuration:
    cache-enabled: true
    default-executor-type: simple
    default-statement-timeout: 25
    jdbc-type-for-null: 'null'
    lazy-loading-enabled: false
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
  mapper-locations:
    - classpath:com/jun/clonestar/**/mapper/*.xml

server:
  error:
    include-exception: true
    include-stacktrace: never
    path: /error
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
    url: jdbc:mysql://192.168.0.186:3306/kbz?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: '*%(web)^('
    username: webkbz