
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/clonestar?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: jun1234
    username: jun

    servlet:
      multipart:
        enabled: true
        max-file-size: 2MB

mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:com/jun/clonestar/**/mapper/*.xml

#file:
#  path:
#    upload-images: E:/cloneStar/src/main/resources/upload